omis/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^bckdr/', admin.site.urls),
    url(r'^tour/', include('landing.urls')),
    url(r'^', include('sharing.urls', namespace='landing')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # Debug Toolbar Stuff
    # import debug_toolbar
    # urlpatterns += [url(r'^__debug__/', include(debug_toolbar.urls)),]

sharing/urls.py
from django.conf.urls import url
from . import views

app_name = 'sharing'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^signup/$', views.UserFormView.as_view(), name='signup'),
    url(r'^all/(?P<page>[\d]+)?$', views.show_page, name='all'),
    url(r'^popular/(?P<page>[\d]+)?$', views.show_page, name='popular'),
    url(r'^star/(?P<page>[\d]+)?$', views.show_page, name='star'),
    url(r'^starred/$', views.starred, name='starred'),
    url(r'^login/$', views.login_user, name='login'),
    url(r'^logout/$', views.logout_user, name='logout'),
    url(r'^u/(?P<user>[\w]+)?/?(starred)?/?(?P<page>[\d]+)?$', views.show_user, name='user'),
    url(r'^(?P<slug>[\w]+)/(?P<sorting>[\w]+)?$', views.detail, name='detail'),
    url(r'^(?P<slug>[\w]+)/del/$', views.delete, name='del'),
]

sharing/models.py
from django.contrib.sessions.models import Session
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from django.db import models
from imagekit.models import ImageSpecField, ProcessedImageField
from imagekit.processors import ResizeToFill, ResizeToFit
from time import strftime

from .tools import *
from .validators import *

PROC_IMG_W = 2048
PROC_IMG_H = 2048
PROC_IMG_Q = 90
SRC_IMG_MAX = 7340032  # In bytes. Count as xMB * 1024 ^ 2
THMB_W = 256
THMB_H = 256
THMB_Q = 75
IMG_EXT = ('jpeg', 'jpg', 'gif', 'png', 'tif', 'tiff')
IMG_MIME = ('image/jpeg', 'image/gif', 'image/png', 'image/tiff')


def update_filename(instance, filename):
    """
    The function is for build full filename
    with folder and new filename
    for 'upload_to' attribute
    :return: filepath with filename
    """
    folder = strftime('%H')
    new_filename = instance.slug
    ext = filename.split('.')[-1]
    return '{}/{}.{}'.format(folder, new_filename, ext)


class Image(models.Model):
    """
    Image model
    """
    img = ProcessedImageField(upload_to=update_filename,
                              processors=[ResizeToFit(PROC_IMG_W, PROC_IMG_H, False)],
                              format='JPEG',
                              options={'quality': PROC_IMG_Q},
                              validators=[FileValidator(
                                  max_size=SRC_IMG_MAX,
                                  allowed_extensions=IMG_EXT,
                                  allowed_mimetypes=IMG_MIME)])
    img_thmb = ImageSpecField(source='img',
                              processors=[ResizeToFill(THMB_W, THMB_H)],
                              format='JPEG',
                              options={'quality': THMB_Q})
    desc = models.CharField('Title',
                            max_length=100,
                            help_text='Up to 100 char.',
                            blank=True)
    slug = models.SlugField(max_length=10, unique=True, db_index=True)
    upl_date = models.DateTimeField('Uploaded', auto_now_add=True, db_index=True)
    rev_date = models.DateTimeField('Last reviewed', null=True)
    rev_count = models.PositiveIntegerField('Reviews', default=0)
    star_count = models.PositiveIntegerField('Stars', default=0)
    user = models.ForeignKey(User, default=1, db_index=True)

    # def save(self, *args, **kwargs):
    #     """
    #      Override to add a slug to new image during save
    #     """
    #     if not self.slug:
    #         self.slug = gen_slug()
    #     super(Image, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('sharing:detail', kwargs={'slug': self.slug})

    def delete(self, *args, **kwargs):
        """
        Override to clean up a garbage upon an object deletion
        """
        # TODO: Wait for CACHE deletion method
        self.img.delete(save=False)
        super(Image, self).delete(*args, **kwargs)

    def __str__(self):
        return '{} - {}'.format(self.slug, self.desc)


class Starred(models.Model):
    """
    Model for unique star count
    """
    image = models.ForeignKey(Image, db_index=True, blank=True)
    user = models.ForeignKey(User, default=1, db_index=True)
    star_date = models.DateTimeField(auto_now_add=True, db_index=True)

    def __str__(self):
        return '{} - {}'.format(self.image_id, self.user)


class Seen(models.Model):
    """
    Model for unique image review count
    """
    image = models.ForeignKey(Image, db_index=True, blank=True)
    session = models.TextField(db_index=True, blank=False)

    def __str__(self):
        return '{} - {}'.format(self.image_id, self.session)

sharing/forms.py
from django import forms
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _

from .models import Image


class ImageForm(forms.ModelForm):
    # 'Upload a valid image. The file you uploaded was either not an image or a corrupted image.'
    msg = _('Not allowed file type or corrupted file')
    img = forms.ImageField(error_messages={'invalid_image': msg})

    class Meta:
        model = Image
        fields = ['img', 'desc']
        widgets = {
            'desc': forms.TextInput(attrs={
                'autocomplete': 'off',
                'class': 'form-control text-center',
                'placeholder': 'Image Title'
            }),
        }


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['email', 'username', 'password']
        msg = _('Oops. We already have one here')
        error_messages = {
            'username': {
                'unique': msg,
            },
        }

        css_class = 'form-control'
        widgets = {
            'email': forms.EmailInput(attrs={
                'autocomplete': 'off',
                'class': css_class,
                'required': 'true',
            }),
            'username': forms.TextInput(attrs={
                'class': css_class,
            }),
            'password': forms.PasswordInput(attrs={
                'class': css_class,
            }),
        }

sharing/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import F
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _
from django.views.generic import View

from .forms import UserForm, ImageForm
from .models import Image, Starred, Seen
from .tools import *

# Initial constants
IMAGE_COUNT = 6
IMAGE_COUNT_PAGINATOR = IMAGE_COUNT * 6


def index(request):
    """
    Main page view
    """
    if 'tour' not in request.COOKIES:
        response = redirect('tour')
        response.set_cookie('tour', 'False')
        return response

    else:
        if request.method == 'POST':
            form = ImageForm(request.POST, request.FILES)
            if form.is_valid():
                image = form.save(commit=False)
                image.user = request.user
                image.slug = gen_slug()
                image.save()
                messages.add_message(request, messages.SUCCESS, _('Yee haw! Your amazing image uploaded'))
                return redirect('sharing:index')
            else:
                # Clear image title if not valid
                form.data.pop('desc')
        else:
            form = ImageForm()

        images_recent = Image.objects.order_by('-upl_date')[:IMAGE_COUNT]
        images_popular = Image.objects.order_by('-rev_count')[:IMAGE_COUNT]
        images_star = Image.objects.order_by('-star_count')[:IMAGE_COUNT]
        context = {
            'form': form,
            'images_recent': images_recent,
            'images_popular': images_popular,
            'images_star': images_star
        }
        return render(request, 'sharing/index.html', context)


class UserFormView(View):
    """
    User signup form
    """
    form_class = UserForm
    template_name = 'sharing/signup.html'

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            user = form.save(commit=False)
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            messages.add_message(request, messages.SUCCESS, _('Welcome to OMIS!'))
            user = authenticate(username=username, password=password)

            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('sharing:index')

        return render(request, self.template_name, {'form': form})


def login_user(request):
    """
    User login view
    """
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                messages.add_message(request, messages.INFO, 'Namaste, stargazer!')
                return redirect('sharing:index')
                # TODO: Fix inactive user behavior here. It needs to write custom authenticate()
                # else:
                #     return render(request, 'sharing/login.html', {'error_message': 'The Account Has Been Disabled'})
        else:
            msg = _('We don’t recognize you')
            return render(request, 'sharing/login.html', {'error_message': msg})
    return render(request, 'sharing/login.html')


def logout_user(request):
    """
    User logout view
    """
    logout(request)
    messages.add_message(request, messages.INFO, _('{}! We will miss you'.format(greetwell('bye'))))
    return redirect('sharing:index')


def show_page(request, page):
    """
     Show Image set view
    """
    if '/popular/' in request.path:
        images = Image.objects.order_by('-rev_count')
    elif '/star/' in request.path:
        images = Image.objects.order_by('-star_count')
    else:
        images = Image.objects.order_by('-upl_date')

    paginator = Paginator(images, IMAGE_COUNT_PAGINATOR)
    try:
        images = paginator.page(page)
    except PageNotAnInteger:
        images = paginator.page(1)
    except EmptyPage:
        images = paginator.page(paginator.num_pages)
    return render(request, 'sharing/set.html', {'images': images})


def show_user(request, user, page):
    """
    Show images by user view
    """
    if user is not None:
        try:
            user_id = User.objects.get(username=user)
        except User.DoesNotExist:
            messages.add_message(request, messages.ERROR, _('We aren’t familiar with an artist'))
            return redirect('sharing:index')

        if '/starred/' in request.path:
            # TODO: Add this queryset ordering by '-star_date'
            user_image_set = \
                Image.objects.filter(id__in=Starred.objects.filter(user=user_id).values('image')).order_by('-upl_date')
            stars = True
        else:
            user_image_set = Image.objects.filter(user=user_id).order_by('-upl_date')
            stars = False

        paginator_image_set = list(user_image_set)

        paginator = Paginator(paginator_image_set, IMAGE_COUNT_PAGINATOR)
        try:
            images = paginator.page(page)
        except PageNotAnInteger:
            images = paginator.page(1)
        except EmptyPage:
            images = paginator.page(paginator.num_pages)
        return render(request, 'sharing/set.html', {
            'stars': stars,
            'greeting': greetwell('hi'),
            'user_name': user,
            'images': images
        })
    else:
        messages.add_message(request, messages.ERROR, _('No artist specified'))
        return redirect('sharing:index')


def detail(request, slug, sorting):
    """
    Image detail view
    """
    # Get a previous URL or get home
    try:
        previous_page = request.META['HTTP_REFERER']
    except KeyError:
        previous_page = '/'

    image = get_object_or_404(Image, slug=slug)
    star_flag = Starred.objects.filter(image=image.id, user=request.user.id).count()

    if sorting == 'popular':
        order = '-rev_count'
    elif sorting == 'star':
        order = '-star_count'
    elif sorting == 'upload':
        order = '-upl_date'
    elif sorting == 'user':
        order = '-upl_date'
    else:
        order = '-id'

    if sorting == 'user':
        images = Image.objects.filter(user=image.user_id).order_by(order)
    else:
        images = Image.objects.order_by(order)

    _count = 0
    for _item in images:
        if _item == image:
            break
        else:
            _count += 1

    if order == '-id':
        next_image = prev_image = None
    else:
        next_image = images[_count - 1].slug if _count > 0 else None
        prev_image = images[_count + 1].slug if _count < (len(images) - 1) else None

    request.session.set_expiry(60 * 60 * 24)

    if str(request.user) is not 'AnonymousUser':
        session_key = request.user.id
    else:
        request.session.save()
        session_key = request.session.session_key

    image_seen = Seen.objects.filter(image=image.id, session=session_key).exists()

    if not image_seen:
        session = Seen()
        session.image_id = image.id
        session.session = session_key
        session.save()

        image.rev_count = F('rev_count') + 1
        image.rev_date = timezone.now()
        image.save()
        image.refresh_from_db()

    try:
        user_name = User.objects.get(id=image.user_id)
    except User.DoesNotExist:
        user_name = 'unknown'

    return render(request, 'sharing/detail.html', {
        'star_flag': star_flag,
        'footer': 'nofooter',
        'sorting': sorting,
        'next_image': next_image,
        'prev_image': prev_image,
        'previous_page': previous_page,
        'image': image,
        'user_name': user_name
    })


def starred(request):
    """
    User-dependent AJAX-based star counter
    """
    slug = request.POST.get('slug', None)
    # star_count = 0
    star_flag = False

    if slug:
        image = Image.objects.get(slug=slug)
        if image:
            star_flag = Starred.objects.filter(image=image.id, user=request.user.id).count()

            if star_flag:
                Starred.objects.filter(image=image.id, user=request.user.id).delete()
                star_flag = False
                if image.star_count > 0:
                    image.star_count = F('star_count') - 1
            else:
                star = Starred()
                star.image_id = image.id
                star.user = request.user
                star.save()
                star_flag = True
                image.star_count = F('star_count') + 1

            image.save()
            image.refresh_from_db()

    return JsonResponse({'star_count': image.star_count, 'star_flag': star_flag})


def delete(request, slug):
    """
     Delete image view
    """
    image = Image.objects.get(slug=slug)
    image.delete()
    messages.add_message(request, messages.SUCCESS, _('Your image deleted'))
    # Get logged in user for correct redirect to a cabinet
    user = str(request.user)
    return redirect('sharing:user', user)

sharing/templates/sharing/base.html
{% load staticfiles %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no" />
    <meta name="format-detection" content="telephone=no" />
    <meta name="Copyright" content="Awesome Team at OMIS" />
    <meta name="theme-color" content="#7cad37" /><!-- Color theme for Chrome -->
    <meta name="mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" /><!-- Color theme for iOS -->
    <meta name="msapplication-navbutton-color" content="#7cad37" /><!-- Color theme for Winphone -->
    <meta name="description" content="OMIS. One More Image Share" />
    <meta name="keywords" content="image sharing, photo" />
    <title>OMIS | {% block title %}{% endblock %}</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'sharing/img/favicon.png' %}" />
    <link rel="stylesheet" href="{% static 'sharing/css/vendor.min.css' %}" />
    <link rel="stylesheet" href="{% static 'sharing/css/app.min.css' %}" />
  </head>
  <body>
    {% block header %}
      {% include "sharing/includes/_header.html" %}
    {% endblock %}

    <div class="statusbar">
    {% block message %}
    {% endblock %}
    </div>

    <main>
      <div class="container">
        <div class="row text-center">
          <section class="col-sm-12 col-sm-offset-0 col-xs-12 col-xs-offset-0">
            {% block content %}
            {% endblock %}
          </section>

          {% block form %}
          {% endblock %}
        </div>
      </div>

      {% block detail %}
      {% endblock %}
    </main>

    {% if footer != 'nofooter' %}
      {% block footer %}
          {% include "sharing/includes/_footer.html" %}
      {% endblock %}
    {% endif %}

    <script src="{% static 'sharing/js/vendor.min.js' %}"></script>
    <script src="{% static 'sharing/js/app.min.js' %}"></script>
  </body>
</html>

sharing/templates/sharing/index.html
{% extends 'sharing/base.html' %}
{% block title %}One More Image Share{% endblock %}

{% block message %}
  {% if messages %}
    {% for message in messages %}
      <div{% if message.tags %} id="alert-dismiss" class="alert alert-{{ message.tags }} text-center"{% endif %}>
        <b class="animated fadeIn">{{ message }}</b>
      </div>
    {% endfor %}
  {% endif %}

  {% if error_message %}
    <div id="alert-dismiss" class="alert alert-danger text-center" role="alert">
      <b>{{ error_message }}</b>
    </div>
  {% endif %}

  {% if form.img.errors %}
    {% for error in form.img.errors %}
    <div id="alert-dismiss" class="alert alert-danger text-center" role="alert">
      <b class="animated fadeIn">{{ error|escape }}</b>
    </div>
    {% endfor %}
  {% endif %}
{% endblock message %}

{% block content %}
        <section class="row">
          <div class="col-sm-8 col-sm-offset-2 col-xs-10 col-xs-offset-1">
            {% if user.is_authenticated %}
              {% include 'sharing/includes/_form_img.html' %}
            {% else %}
              <h3 class="darkgray intro-margin">
                <i class="fa fa-eye color-primary-dark"></i> Incog.
                <i class="fa fa-pencil-square-o lightgray"></i> or
                <i class="fa fa-sign-in lightgray"></i> to
                <i class="fa fa-upload lightgray"></i> and
                <i class="fa fa-star color-secondary"></i>
              </h3>
            {% endif %}
          </div>
        </section>

        <section class="row">
          <div class="col-xs-12">
            <h3 class="text-left"><a href="{% url 'sharing:all' %}1">Recent</a></h3>
            <div class="row">
              {% for image in images_recent %}
                <div class="col-sm-2 col-xs-4 sidepadding-adj">
                  <figure class="thumbnail">
                    <a href="{% url 'sharing:detail' image.slug %}upload">
                      <img src="{{ image.img_thmb.url }}"
                           alt="{{ image.desc }}"
                           title="{{ image.desc }}" />
                    </a>
                    <figcaption class="thumbnail-footer text-center">
                      <div class="col-xs-6 nopadding">
                        <i class="fa fa-eye color-primary"></i> {{ image.rev_count }}
                      </div>
                      <div class="col-xs-6 nopadding">
                        <i class="fa fa-star color-secondary"></i> {{ image.star_count }}
                      </div>
                    </figcaption>
                  </figure>
                </div>
              {% endfor %}
            </div>

            <h3 class="text-left"><a href="{% url 'sharing:popular' 1 %}">Popularity</a></h3>
            <div class="row">
              {% for image in images_popular %}
                <div class="col-sm-2 col-xs-4 sidepadding-adj">
                  <figure class="thumbnail">
                    <a href="{% url 'sharing:detail' image.slug %}popular">
                      <img src="{{ image.img_thmb.url }}"
                           alt="{{ image.desc }}"
                           title="{{ image.desc }}" />
                    </a>
                    <figcaption class="thumbnail-footer text-center">
                      <div class="col-xs-6 nopadding">
                        <i class="fa fa-eye color-primary"></i> {{ image.rev_count }}
                      </div>
                      <div class="col-xs-6 nopadding implicit">
                        <i class="fa fa-star color-secondary"></i> {{ image.star_count }}
                      </div>
                    </figcaption>
                  </figure>
                </div>
              {% endfor %}
            </div>

            <h3 class="text-left"><a href="{% url 'sharing:star' 1 %}">Stars</a></h3>
            <div class="row">
              {% for image in images_star %}
                <div class="col-sm-2 col-xs-4 sidepadding-adj">
                  <figure class="thumbnail">
                    <a href="{% url 'sharing:detail' image.slug %}star">
                      <img src="{{ image.img_thmb.url }}"
                           alt="{{ image.desc }}"
                           title="{{ image.desc }}" />
                    </a>
                    <figcaption class="thumbnail-footer text-center">
                      <div class="col-xs-6 nopadding implicit">
                        <i class="fa fa-eye color-primary"></i> {{ image.rev_count }}
                      </div>
                      <div class="col-xs-6 nopadding">
                        <i class="fa fa-star color-secondary"></i> {{ image.star_count }}
                      </div>
                    </figcaption>
                  </figure>
                </div>
              {% endfor %}
            </div>

          </div>
        </section>
{% endblock content %}

sharing/templates/sharing/login.html
{% extends 'sharing/base.html' %}
{% block title %}Log In{% endblock %}

{% block message %}
  {% if error_message %}
    <div id="alert-dismiss" class="alert alert-danger text-center" role="alert">
      <b class="animated fadeIn">{{ error_message }}</b>
    </div>
  {% endif %}
{%  endblock %}

{% block form %}
          <section class="form-container col-lg-4 col-lg-offset-4 col-sm-6 col-sm-offset-3 col-xs-10 col-xs-offset-1 animated slideInDown">
            <div class="panel panel-default" style="display: inline-block;">
              <div class="panel-body nopadding">
                <h3><i class="fa fa-sign-in"></i> Log In</h3>

                <form class="form-horizontal"
                      role="form"
                      action="{% url 'sharing:login' %}"
                      method="post"
                      enctype="multipart/form-data">{% csrf_token %}

                  <div class="form-group">
                    <div class="col-sm-8 col-sm-offset-2 col-xs-10 col-xs-offset-1">
                      <div class="input-group">
                        <span class="input-group-addon" id="basic-addon3">
                          <i class="fa fa-male"></i>
                        </span>
                        <input id="id_username"
                               class="form-control"
                               maxlength="30"
                               name="username"
                               type="text">
                      </div>
                    </div>
                  </div>

                  <div class="form-group">
                    <div class="col-sm-8 col-sm-offset-2 col-xs-10 col-xs-offset-1">
                      <div class="input-group">
                        <span class="input-group-addon" id="basic-addon3">
                          <i class="fa fa-key"></i>
                        </span>
                        <input id="id_password"
                               class="form-control"
                               maxlength="30"
                               name="password"
                               type="password">
                      </div>
                    </div>
                  </div>

                  <div class="form-group">
                    <button type="submit" class="btn btn-success">
                      <i class="fa fa-sign-in"></i> Log In
                    </button>
                  </div>
                </form>

              </div>

              <div class="panel-footer">
                <a href="{% url 'sharing:signup' %}">Sign Up</a> Instead.<br />
                <a href="{% url 'sharing:index' %}">Continue</a> Incog.
              </div>
            </div>
          </section>
{% endblock form %}

sharing/templates/sharing/set.html
{% extends 'sharing/base.html' %}
{% load staticfiles %}

{% block title %}
  {% if user.get_username in request.path %}
    Your Images
  {% elif '/u/' in request.path %}
    Images of {{ user_name }}
  {% elif '/popular/' in request.path %}
    Images by Popularity
  {% elif '/star/' in request.path %}
    Images by Stars
  {% else %}
    Recent Images
  {% endif %}
{% endblock %}

{% block message %}
  {% if messages %}
    {% for message in messages %}
      <div{% if message.tags %} id="alert-dismiss" class="alert alert-{{ message.tags }} text-center"{% endif %}>
        <b class="animated fadeIn">{{ message }}</b>
      </div>
    {% endfor %}
  {% endif %}
{% endblock %}

{% block content %}
          <section>
            {% if user.is_authenticated and user.get_username in request.path %}
              <h2 class="text-right animated fadeIn">{{ greeting }}, {{ user }}!</h2>
              <h3 class="text-left">
                <i class="fa fa-upload"></i>
                {% if stars %}<a href="/u/{{ user_name }}">{% endif %}Yours{% if stars %}</a>{% endif %} |
                <i class="fa fa-star{% if stars %} color-secondary{% endif %}"></i>
                {% if not stars %}<a href="/u/{{ user_name }}/starred/">{% endif %}Starred{% if not stars %}</a>{% endif %}
              </h3>
              {% if not images %}
                <h4>{% if not stars %}
                      It’s a pity you didn’t share anything yet{% else %}
                      Unfortunately you didn’t fave anything so far{% endif %}.</h4>
                <h4>{% if not stars %}
                      Feel free to upload something beautiful on the <a href="{% url 'sharing:index' %}">Homepage</a>
                    {% else %}
                      Visit the <a href="{% url 'sharing:index' %}">Homepage</a> and star images you like{% endif %}.</h4>
              {% endif %}
            {% else %}
              {% if not images %}
                <h3>{{ user_name }} didn’t share any image yet.</h3>
                <h4>The emptiness is all around.</h4>
              {% else %}
                <h3 class="text-left">
                  {% if '/popular/' in request.path %}
                    Images by Popularity
                  {% elif '/star/' in request.path %}
                    Images by Stars
                  {% elif '/u/' in request.path %}
                    Images of {{ user_name }}
                  {% else %}
                    Recent Images
                  {% endif %}
                </h3>
              {% endif %}
            {% endif %}
          </section>

          <section>
            <div class="row">
            {% if images %}
              {% for image in images %}
                <div class="col-sm-2 col-xs-4 sidepadding-adj">
                  <figure class="thumbnail">
                    <a href="{% url 'sharing:detail' image.slug %}{% if '/popular/' in request.path %}popular{% elif '/star/' in request.path %}star{% elif '/all/' in request.path %}upload{% elif '/u/' in request.path %}user{% endif %}">
                      <img src="{{ image.img_thmb.url }}"#}
                           alt="{{ image.desc }}"
                           title="{{ image.desc }}" />
                    </a>
                    {% if user.is_authenticated and user.get_username in request.path and not stars %}
                      <figcaption class="thumbnail-footer text-center">
                        <a href="{% url 'sharing:del' image.slug %}">
                          <i class="fa fa-trash-o text-danger"></i>
                        </a>
                      </figcaption>
                    {% else %}
                      <figcaption class="thumbnail-footer text-center">
                        <div class="col-xs-6 nopadding
                                    {% if '/star/' in request.path %}implicit{% endif %}">
                          <i class="fa fa-eye color-primary"></i> {{ image.rev_count }}
                        </div>
                        <div class="col-xs-6 nopadding
                                    {% if '/popular/' in request.path %}implicit{% endif %}">
                          <i class="fa fa-star color-secondary"></i> {{ image.star_count }}
                        </div>
                      </figcaption>
                    {% endif %}
                  </figure>
                </div>
                {% if forloop.counter|divisibleby:6 and not forloop.last %}
                  </div>
                  <div class="row">
                {% endif %}
              {% endfor %}
              {# It's not an error here about unclosed div #}
           </section>

            {% if images.has_other_pages %}
              <section>
                <ul class="pagination">
                  {% if images.has_previous %}
                    <li>
                      <a href="{{ images.previous_page_number }}">
                        <i class="fa fa-angle-left"></i> Prev</a>
                    </li>
                  {% endif %}
                  {% for page in images.paginator.page_range %}
                    <li class="{% if images.number == page %}active{% endif %}">
                      <a href="{{ page }}">{{ page }}</a>
                    </li>
                  {% endfor %}
                  {% if images.has_next %}
                    <li>
                      <a href="{{ images.next_page_number }}">Next
                        <i class="fa fa-angle-right"></i>
                      </a>
                    </li>
                  {% endif %}
                </ul>
              </section>
            {% endif %}
          {% endif %}
{% endblock content %}